### ISSUE TITLE
First time signup return HTTP Status Code 500

### ISSUE THREAD

**Issue by sagarpatke** [stackroute/quizart-social#2]
Error Log:

http-server0              | 2016-08-21T05:51:56.022Z 08jw06q9rhlx/1471758680025/15/- WARN       act     -               -       -       seneca: No matching action patte  cmd: 'create' }, and no default result provided (using a default$ property).: 'sagarpatke@gmail.com', username: 'sagarpatke@gmail.com',
http-server0              |     at Object.errormaker [as error](/usr/src/service/node_modules/eraro/eraro.js:94:15)
http-server0              |     at Object.execute_action [as fn](/usr/src/service/node_modules/seneca/seneca.js:1102:25)
http-server0              |     at Immediate.<anonymous> (/usr/src/service/node_modules/gate-executor/gate-executor.js:136:14)
http-server0              |     at runCallback (timers.js:574:20)
http-server0              |     at tryOnImmediate (timers.js:554:5)
http-server0              |     at processImmediate [as _immediateCallback](timers.js:533:5)
http-server0              | 2016-08-21T05:51:56.023Z 08jw06q9rhlx/1471758680025/15/- ERROR      act     -               OUT             -       6       {username:sagarpatke@gmail.com,useravatar:,name:Sagar Patke,age:null,country:NA,totalGames:0,liketopics:,follow ENTRY           -       seneca: No matching action pattern found for { u  cmd: 'create' }, and no default result provided (using a default$ property).: 'sagarpatke@gmail.com', username: 'sagarpatke@gmail.com',
http-server0              |     at Object.errormaker [as error](/usr/src/service/node_modules/eraro/eraro.js:94:15)
http-server0              |     at Object.execute_action [as fn](/usr/src/service/node_modules/seneca/seneca.js:1102:25)
http-server0              |     at Immediate.<anonymous> (/usr/src/service/node_modules/gate-executor/gate-executor.js:136:14)
http-server0              |     at runCallback (timers.js:574:20)
http-server0              |     at tryOnImmediate (timers.js:554:5)
http-server0              |     at processImmediate [as _immediateCallback](timers.js:533:5)

**Comment by sagarpatke** [comment]
Resolved. Need to make sure that microservice-profile has to be connected to the mesh first.
